.MODEL SMALL 
.STACK 100H 
.DATA 
ENTFNUM DB 13,10,'Enter first two digits number',13,10,'$' 
ENTSNUM DB 13,10,'Enter second two digits number',13,10,'$'
RESULT DB 13,10,'gcd(xx,xx)= xx ',13,10,'$'
q1 DB ?  
q2 DB ?
t DB ?
TEN DB 10
TWO DB 2
.CODE
MOV AX,@DATA
MOV DS,AX
MOV AX,0  
; ASK THE USE TO ENTER TWO DIGITS NUMBER 
MOV AH,9
MOV DX,OFFSET ENTFNUM
INT 21H
; INPUT THE FIRST DIGIT
MOV AH,1
INT 21H
MOV AH,0
; PUT THE FIRST DIGIT IN RESULT STRING 
MOV RESULT[6],AL
SUB AL,'0'
; MULTIPICATION IN TEN 
MUL TEN
MOV q1,AL
; INPUT THE SECOND DIGIT 
MOV AH,1
INT 21H
MOV AH,0
; PUT THE SECOND DIGIT IN RESULT STRING
MOV RESULT[7],AL
SUB AL,'0'
ADD q1,AL
; ASK THE USER TO ENTER THE SECOND NUMBER 
MOV AH,9
MOV DX,OFFSET ENTSNUM
INT 21H
; INPUT THE FIRST DIGIT
MOV AH,1
INT 21H
MOV AH,0
; PUT THE DIGIT IN RESULT STRING
MOV RESULT[9],AL
SUB AL,'0'
; MULTIPICATION IN TEN
MUL TEN
MOV q2,AL
; INPUT THE SECOND DIGIT
MOV AH,1
INT 21H
MOV AH,0
; PUT THE DIGIT IN RESULT STRING
MOV RESULT[10],AL
SUB AL,'0'
ADD q2,AL
MOV AL,q2
; EXCHNGE BETWEEN q1 AND q2 IF q2 IS BIGGER THAN q1
CMP q1,AL
JA NOEXCHANGE
XCHG q1,AL
MOV q2,AL
NOEXCHANGE:
MOV AX,0
; CALCULATE THE MUTUAL DIVIDER 
MOV CX,5
BODY:
CMP q2,0
JE NEXTSTAGE
MOV AL,q1
MOV AH,0
DIV q2
MOV t,AH
MOV AH,0
MOV AL,t
MUL TWO
CMP q2,AL
JNBE BODY1
MOV AL,0
MOV AL,q2
SUB AL,t
MOV t,AL
MOV AL,0
BODY1:
MOV AL,q2
MOV q1,AL
MOV AL,0
MOV AL,t
MOV q2,AL
LOOP BODY
NEXTSTAGE:
MOV AX,0
MOV AL,q1
MOV AH,0
DIV TEN
ADD AL,'0'
; PUT THE SECOND DIGIT OF THE MUTUAL DIVDER IN RESULT STRING
MOV RESULT[14],AL
ADD AH,'0'
;PUT THE FIRST DIGIT OF THE MUTUAL DIVDER IN RESULT STRING
MOV RESULT[15],AH
MOV DX,OFFSET RESULT 
; PRINTS RESULT STRING AND END THE PROGRAM 
DISPLAYGREETING:
MOV AH,9
INT 21H
MOV AH,4CH
INT 21H
END
